"""cart

Revision ID: 0f4505649e61
Revises: 18176583b892
Create Date: 2022-10-13 16:02:28.059294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4505649e61'
down_revision = '18176583b892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.drop_index('ix_cart_user_id', table_name='cart')
    op.create_index(op.f('ix_cart_customer_id'), 'cart', ['customer_id'], unique=False)
    op.drop_constraint('cart_user_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'customers', ['customer_id'], ['id'])
    op.drop_column('cart', 'user_id')
    op.drop_constraint('cart_items_cart_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'cart', ['cart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key('cart_items_cart_id_fkey', 'cart_items', 'customers', ['cart_id'], ['id'])
    op.add_column('cart', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_user_id_fkey', 'cart', 'customers', ['user_id'], ['id'])
    op.drop_index(op.f('ix_cart_customer_id'), table_name='cart')
    op.create_index('ix_cart_user_id', 'cart', ['user_id'], unique=False)
    op.drop_column('cart', 'customer_id')
    # ### end Alembic commands ###
