"""users table

Revision ID: 425c00a2611b
Revises: df781a46a9fd
Create Date: 2022-10-11 16:06:36.299079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425c00a2611b'
down_revision = 'df781a46a9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_products_color'), 'products', ['color'], unique=False)
    op.create_index(op.f('ix_products_created_date'), 'products', ['created_date'], unique=False)
    op.create_index(op.f('ix_products_gender'), 'products', ['gender'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('ix_products_size'), 'products', ['size'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_size'), table_name='products')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_gender'), table_name='products')
    op.drop_index(op.f('ix_products_created_date'), table_name='products')
    op.drop_index(op.f('ix_products_color'), table_name='products')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
