"""user table

Revision ID: 75e5ddea2cbb
Revises: 0f4505649e61
Create Date: 2022-10-14 15:36:13.428180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e5ddea2cbb'
down_revision = '0f4505649e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('role', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_customers_role'), 'customers', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_role'), table_name='customers')
    op.drop_column('customers', 'role')
    # ### end Alembic commands ###
