"""address table

Revision ID: f167cf86726a
Revises: f5284f97b9a9
Create Date: 2022-10-12 19:36:07.316555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f167cf86726a'
down_revision = 'f5284f97b9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'address', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    # ### end Alembic commands ###
